stages:
  - build
  - deploy

build:
  stage: build
  image: gcr.io/kaniko-project/executor:v1.9.0-debug
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile.production" --destination "${CI_REGISTRY_IMAGE}/litter-application:${CI_COMMIT_TAG:-latest}"

deploy:
  stage: deploy
  image: gcr.io/k8s-skaffold/skaffold:v2.8.0
  when: manual
  script:
    - kubectl config use-context $K8S_CONTEXT
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD --dry-run=client -o yaml | kubectl apply -f -
    - skaffold deploy --profile production --images ${CI_REGISTRY_IMAGE}/litter-application:${CI_COMMIT_TAG:-latest}
    - kubectl get deployments
    - kubectl get pods
    - kubectl get services
