apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging
  namespace: staging
  annotations:
    # Add any specific annotations here, if needed
spec:
  ingressClassName: nginx
  rules:
  - host: qa-cscloud7-103.lnu.se  # Update this with the actual subdomain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: litter-staging
            port:
              number: 8888
