apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging
  namespace: staging
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - qa-cscloud7-103.lnu.se
    secretName: staging-tls-secret2
  rules:
  - host: qa-cscloud7-103.lnu.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: litter-staging
            port:
              number: 8888
